### ISSUE TITLE
Decompress Downloaded Sample Code

### ISSUE THREAD

**Issue by hbisneto** [hbisneto/PyBridge#47]
After downloading sample code, decompress the "main.zip" file

**Comment by sagarsadhu** [comment]
Hi @hbisneto , I am interested to work on this.

**Comment by hbisneto** [comment]
Hi @sagarsadhu, that would be great to be helped on this. You can Pull-Request at any time. Your name will be in the update log :)

**Comment by sagarsadhu** [comment]
Hi @hbisneto , Please check https://github.com/hbisneto/PyBridge/pull/49 and notify me if you need any changes.

**Comment by hbisneto** [comment]
> Hi @hbisneto , Please check #49 and notify me if you need any changes.

@sagarsadhu It was an awesome job! You made it! I merged your pull-request to the branch `v1.3`. 
I'm opened to new implementation ideas! ;)

Thank you! Cheers! :)
