### ISSUE TITLE
Project Completion Time

### ISSUE THREAD

**Issue by hbisneto** [hbisneto/PyBridge#86]
Add time for creating the project. "You project was created in XX seconds."

If time took less than 1 second, "Your project was created in less than a second"

All the options should show the real time it took to complete the project creation

**Comment by arshadshk246** [comment]
Sir I have solved the issue by using the time module. I have changed the Core.py files of Linux, Mac and Windows. Can you please check the pull request.

**Comment by hbisneto** [comment]
Issue solved in #87 

@arshadshk246 Thank you for solving this issue. Your commit has been added to the "main" branch :)

Thank you!
